[package]
name = "ress_ts_test"
version = "0.1.0"
authors = ["rfm <r@robertmasen.pizza>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ress = "0.7"
flate2 = "1"
reqwest = "0.9"
tar = "0.4"
walkdir = "2"